### ISSUE TITLE
date formatting

### ISSUE THREAD

**Issue by mmw590** [forc-db/ForC#6]
@teixeirak 
weird date formatting in plothistory, perhaps due to autoformatting in Excel?
needs to be unambiguous, ideally in YYYY-MM-DD format.

**Comment by teixeirak** [comment]
We also appear to have a date error in the measurements file, start date for lines 2288,2289,2302, and 2303.

**Comment by teixeirak** [comment]
this has been fixed for the plothistory file.

**Comment by teixeirak** [comment]
Dates in the measurements file have been reformatted, and incorrect dates identified above fixed.

**Comment by mmw590** [comment]
There were more date errors in plothistory. The formatting did not stick (Excel is really annoying in this aspect- you have to change your computer settings in order to change Excel's default date format, even for csv). 

Also, Excel doesn't recognize dates before 1900. If Excel automatically changes the date format to something else (like m/d/yy), the dates before 1900 will not get changed (1600-01-01). 

I'll do these things tomorrow:
1. Reformat the dates in plothistory and measurements with an unambiguous date format (yyyy-mm-dd), and then replace the files on GitHub. 
2. Edit the metadata to say dates are in yyyy-mm-dd format.

Not sure how to prevent Excel from changing the date format besides 1. changing your computer settings in order to change Excel's default date format; 2. always checking the date format before saving in Excel

https://answers.microsoft.com/en-us/msoffice/forum/msoffice_excel-mso_windows8/how-do-i-permanently-change-date-format-06-jun-to/a02c9e56-756e-484b-8fa2-852e71919042

**Comment by mmw590** [comment]
Date issues persists, particularly with dates in early 1900s! Need to find uncontaminated version of plothistory with correct dates.

**Comment by teixeirak** [comment]
Is this just plothistory or also measurements?

Are they correct in the master version in ForC_private?

**Comment by teixeirak** [comment]
This is fixedin plothistory. @mmw590, Is it also a problem for measurements?

**Comment by teixeirak** [comment]
I checked the measurements file, and confirmed that dates are correct. Closing this issue.
